### ISSUE TITLE
hl-mode doesn't work in ruby-mode

### ISSUE THREAD

**Issue by bbatsov** [tarsius/hl-todo#80] opened 2024-01-24 12:24 UTC
Today I've noticed that annotations in one Ruby source file are not highlighted by `hl-mode`, even if `global-hl-mode` is enabled. In all other major modes I've tried it seems to work fine. Any ideas?

![image](https://github.com/tarsius/hl-todo/assets/103882/9a1e1127-9de6-4925-9958-d95b2479e35c)

**Comment by tarsius** [comment] 2024-01-24 15:49
I cannot reproduce that.

**Comment by bbatsov** [comment] 2024-01-24 15:59
Hmm, yeah, might be some weird interaction with `flyspell-prog-mode`, although I'm not sure why this happens only in `ruby-mode` for me.

**Comment by tarsius** [comment] 2024-03-11 16:52
I don't think there's much I can do here, so I am closing.

Flyspell has to stop highlighting these keywords as errors, or at least it has to stop overriding other highlighting when it highlights them as errors.

**Closed** 2024-03-11 16:52 UTC
