### ISSUE TITLE
Add version metadata to package

### ISSUE THREAD

**Issue by realcomplex** [tarsius/hl-todo#79] opened 2024-01-01 16:54 UTC
Hi. Not an expert in elisp packaging by any means, so sorry if this is just a silly misunderstanding. I'm using elpaca to manage my emacs packages, and it started complaining because magit-todos requires the hl-todo package at some minimum version, but the hl-todo package doesn't seem to really make its version known apart from in git tags. Would it be possible to add a `;; Version: x.y.z` line in the main .el file to make package managers aware of the version?

**Comment by tarsius** [comment] 2024-01-01 17:55
I strongly believe that it is a mistake to use a library header as the source of version information. A release is a pointer to exactly one commit/"version". So is a tag -- which makes it an excellent fit for, well, *tagging* a release.

On the other hand, a string that is part of some file as stored in some commit, cannot be used to unambiguously identify a release. What happens after a maintainer creates a new release, say `1.0`, by bumping the embedded version string and committing the result?

There are basically two options.

(For dramatic effect, let's assume the case where the first commit after the release commit, removes support for an older Emacs release -- i.e., a breaking change.)

1. The embedded version string is not bumped. We now have two commits, which both claiming to be `1.0`.

   If one gets ones hands on a version of some package, outside the context of a version control system (i.e., via package manager or mailing-list) and it contains the string `;; Version: 1.0`, one has **no** way of knowing if that actually is `1.0` of that package. It could be, but it could also be any version after that release, that has not yet been released as `1.1`, `1.0.1` ... yet.

   I believe that back in the old days when everyone embedded versions strings, these version strings got *automatically* bumped on *every* commit, by the version control system (cvs). If you do that, then sure, the version string can be relied on, and I can agree that there is a benefit to that (but also drawbacks, such as cluttering each and every diff).  But that's not what we do nowadays with git; here the original benefit that was used as justification decades ago, has completely disappeared, I would argue turned into a drawback: its easy to fall into the trap of believing this information is accurate, when in fact it (much!) more likely is not (because there usually are >0 commits between releases).

2. The embedded version string is bumped to some string, that while technically a version string, also communicates, "well actually, this is not a release".

   To add insult to injury, Emacs does not support "post-release" version strings. Something like `1.0-devel`. `1.0-git` and some others do exist, but they are all *smaller* than `1.0`. That's only the tip of the iceberg that are the issues with how Emacs does version strings, and I won't go into the details this time around.

   This also assumes that package managers and the software used to publish package archives correctly interprets this information, which I know `elpa-admin.el` (used for [Non]GNU[-devel] ELPA) does not.

3. More likely than actually always bumping the embedded version after after every release, is that we maintainers decide to do it, and then often forget to actually do it.

So no, I won't be embedding version strings in my libraries. It's wrong to do it and I still have some faint hope that we can eventually collectively move away from this mistake.

**Closed** 2024-01-01 17:58 UTC

**Comment by realcomplex** [comment] 2024-01-01 18:58
Thanks for your time and for the great response, this really gave me very good insight into the matter! As I said, I'm not experienced in the emacs packaging universe so I'm very happy to learn best practices. As always, thanks also for your great contributions to so many things emacs.

**Comment by progfolio** [comment] 2024-01-01 22:03
@tarsius

> I strongly believe that it is a mistake to use a library header as the source of version information.
> A release is a pointer to exactly one commit/"version".
> So is a tag -- which makes it an excellent fit for, well, _tagging_ a release.

It's a convenient for the package developer to kick the can.
Not so convenient for package managers.
Git tags are also mutable, which makes them not so great for the same purpose.

> (For dramatic effect, let's assume the case where the first commit after the release commit, removes support for an older Emacs release -- i.e., a breaking change.)

The maintainer of the package can communicate a breaking change by bumping the major version number.
  
>     1. The embedded version string is not bumped. We now have two commits, which both claiming to be `1.0`.

That's a bug on the maintainer's part.

>        If one gets ones hands on a version of some package, outside the context of a version control system (i.e., via package manager or mailing-list) and it contains the string `;; Version: 1.0`, one has **no** way of knowing if that actually is `1.0` of that package.

If they get ahold of the source files outside the context of a VCS, they wouldn't have the git tag or commit at hand either.
If anything, that sounds like an argument *in favor* of embedding a version string in the source files.

>        I believe that back in the old days when everyone embedded versions strings, these version strings got _automatically_ bumped on _every_ commit, by the version control system (cvs).

And now people have largely converged on semantic versioning. 

> ...drawbacks, such as cluttering each and every diff

I don't see how it's "clutter" if you consider the version number to hold semantic meaning.

> But that's not what we do nowadays with git;

Most published elisp packages use the Version header field in the package's main elisp file. Some of those package's use git tags *in addition* to that metadata to publish releases. Very few packages (and even fewer authors) rely solely on git tags.

> 2. The embedded version string is bumped to some string, that while technically a version string, also communicates, "well actually, this is not a release".

Semantic versioning communicates the information clearly when used properly.
It will always boil down to people agreeing on a convention.
Semver is much simpler than all of these bespoke alternative "solutions" (MELPA's YYYYMMDD versioning scheme, the `version-regexp` recipe keyword, etc).

Discovering git tags also doesn't work well with shallow clones.

>     3. More likely than actually always bumping the embedded version after after every release, is that we maintainers decide to do it, and then often forget to actually do it.
> So no, I won't be embedding version strings in my libraries. It's wrong to do it and I still have some faint hope that we can eventually collectively move away from this mistake.

What's the solution you're proposing? Everyone rely solely on git tags? Some other versioning scheme?

**Comment by tarsius** [comment] 2024-01-01 23:06
> > I strongly believe that it is a mistake to use a library header as
> > the source of version information.  A release is a pointer to
> > exactly one commit/"version".  So is a tag -- which makes it an
> > excellent fit for, well, _tagging_ a release.
> 
> It's a convenient for the package developer to kick the can.  Not so
> convenient for package managers.  Git tags are also mutable, which
> makes them not so great for the same purpose.

Using the same logic as you use below, if package authors mutate their
tags, they only have to blame themselves and suffer the consequences.

> > (For dramatic effect, let's assume the case where the first commit
> > after the release commit, removes support for an older Emacs release
> > -- i.e., a breaking change.)
> 
> The maintainer of the package can communicate a breaking change by
> bumping the major version number.

In this scenario the package author refrained from increasing the minimal Emacs
release in a package release because they know how controversial such a change
can be.  Instead they released a version that still supports the same Emacs
releases as before, exactly so they can say "you can still go back to that
release if you need support for Emacs X.  Then they require a newer Emacs
release, on the development branch, which gets published on MELPA.  They do not
immediately create a release so that users can notice the change and make their
opinion heard if it causes issues for them, before this breaking change is
finalized with a release.

Maybe I should have used a less dramatic example: Fix typo in docstring.  In
that case 1.0+"dostring fix" also falsely claims to be 1.0, and creating a
release to prevent that would make no sense, because then the same would apply
to the next release and we don't want to create a release for every commit.

> > The embedded version string is not bumped. We now have two commits,
> > which both claiming to be `1.0`.
> 
> That's a bug on the maintainer's part.

Nearly everybody does this.  I don't do it for Magit because that is such a
popular package, but for my other packages it is not worth the hassle.  I will
probably stop doing it for Magit as well after the next release and just live
with the version information being incorrect.

> >  If one gets ones hands on a version of some package, outside the
> >  context of a version control system (i.e., via package manager or
> >  mailing-list) and it contains the string `;; Version: 1.0`, one has
> >  **no** way of knowing if that actually is `1.0` of that package.
> 
> If they get ahold of the source files outside the context of a VCS,
> they wouldn't have the git tag or commit at hand either.  If anything,
> that sounds like an argument *in favor* of embedding a version string
> in the source files.

I think it is better to provide no version information than to provide
incorrect version information.

> > I believe that back in the old days when everyone embedded versions
> > strings, these version strings got _automatically_ bumped on _every_
> > commit, by the version control system (cvs).
> 
> And now people have largely converged on semantic versioning.
> 
> > ...drawbacks, such as cluttering each and every diff
> 
> I don't see how it's "clutter" if you consider the version number to
> hold semantic meaning.

I can agree to disagree on that one.  However since nobody actually does
bump the version on every commit, this is largely irrelevant.

> > But that's not what we do nowadays with git;
> 
> Most published elisp packages use the Version header field in the
> package's main elisp file.

Linus specifically argued against using embedded version strings in Git's
early days (sorry no reverence).  So "we" here refers to people using Git
as intended by its author, not what the Emacs community has settled on.

> Some of those package's use git tags *in
> addition* to that metadata to publish releases. Very few packages (and
> even fewer authors) rely solely on git tags.

This isn't actually true.  Preparing these statistics is actually on of the very
next things I intend to tackle when it comes to "arguing about version string".

> > 2. The embedded version string is bumped to some string, that while
> >    technically a version string, also communicates, "well actually,
> >    this is not a release".
> 
> Semantic versioning communicates the information clearly when used
> properly.

The question of what format the version strings follow is completely 
orthogonal to the question of where the version strings are located.

> It will always boil down to people agreeing on a
> convention.  Semver is much simpler than all of these bespoke
> alternative "solutions" (MELPA's YYYYMMDD versioning scheme, the
> `version-regexp` recipe keyword, etc).

I agree MELPA's versioning scheme is a disaster.  Fixing that is my primary
goal, when it comes to version strings.  I have largely given up to convince
anyone of anything else when it comes to version strings at this point.
Basically I want to bring sane version strings to Melpa, and then be done with
version strings forever.

> Discovering git tags also doesn't work well with shallow clones.

The use of a shallow clone might mean that the version information is missing,
which is unfortunate.  But again, I would argue that it is better for it to be
missing than wrong.

If the version string is embedded in a file and you use the usual "walk the
history until we find the first commit that introduced that string" approach,
and not all history is available, then this must likely will locate the wrong
commit.

> >     3. More likely than actually always bumping the embedded version
> > after after every release, is that we maintainers decide to do it,
> > and then often forget to actually do it.  So no, I won't be
> > embedding version strings in my libraries. It's wrong to do it and I
> > still have some faint hope that we can eventually collectively move
> > away from this mistake.
> 
> What's the solution you're proposing? Everyone rely solely on git
> tags?

Yes.

And those who insist on using tag+embedded should make absolutely sure they
always tag the very commit that bumped the embedded string.  Package archives
can continue to support embedded strings (by themselves or as duplicated data),
but encourage the use of tags.  Package archives can "embedded" the version by
using it as part of the name of the shipped archive and the top-level directory
(as we already do).

> Some other versioning scheme?

Versioning scheme is orthogonal to where the version information is stored.

----

I don't actually want to argue about this at this time.  It's like spaces vs
tabs, or merge vs rebase.  Sole-sucking really.  I want to achieve something
here and every time I wade unprepared into these conversations, it sucks up
some of the energy that I should preserve to actually get something done in
this domain.

**Comment by progfolio** [comment] 2024-01-02 00:03
> Maybe I should have used a less dramatic example: Fix typo in docstring. In that case 1.0+"dostring fix" also falsely claims to be 1.0

1.0+"docstring fix" = Version: 1.0.1

>and creating a release to prevent that would make no sense, because then the same would apply to the next commit and we don't want to create a release for every commit.

Bumping the version number needn't require *building* a release for every commit.
That should be up to the package author, ELPA tooling, etc.
But what that also allows is for *users* to build their own releases and for you to get the version info from them in a reliable way.

> Nearly everybody does this. I don't do it for Magit because that is such a popular package, but for my other packages it is not worth the hassle. I will probably stop doing it for Magit as well after the next release and just live with the version information being incorrect.

That would be an unfortunate decision.

> I think it is better to provide no version information than to provide incorrect version information.

The version information can be correct, though, if you bump the version string.

> I can agree to disagree on that one. However since nobody actually does bump the version on every commit, this is largely irrelevant.

It's relevant.
"Newer is better" as far as Emacs versions are considered in practice, so we only need to know that a package satisfies a *minimum* version.
That case is covered even if you choose not to bump your version string every commit.
Excluding it altogether leads to breakage or the user having to manually specify the version.

> This isn't actually true. Preparing these statistics is actually on of the very next things I intend to tackle when it comes to "arguing about version string".

I see the same handful of packages popping up over and over again now that I've added version checking to Elpaca.
(Which, as a side note, I added in hopes of sparing users and maintainers hard-to-deal-with bugs. I've now just inherited a different class of bugs due to idosyncratic versioning preferences.)
Hundreds of others I've personally tested do not have this issue.
I'll be interested to see the statistics.
  
> The question of what format the version strings follow is completely orthogonal to the question of where the version strings are located.

It's a practical concern and related to the bigger picutre:
The elisp community should agree on *some* standard regarding versioning.
  
> > Discovering git tags also doesn't work well with shallow clones.
> 
> The use of a shallow clone might mean that the version information is missing, which is unfortunate. But again, I would argue that it is better for it to be missing than wrong.

I've already mentioned how it needn't be wrong. It's just a matter of bumping a "Version:" header appropriately.
Even this could be largely automated, I'm sure.
The only work on the package author's part would be considering what kind of change it is.
Something they should already be doing anyhow.

> If the version string is embedded in a file and you use the usual "walk the history until we find the first commit that introduced that string" approach, and not all history is available, then this must likely will locate the wrong commit.

That doesn't need to be done if the Version is up to date.
You just read the header's value.
Again, bumping the version and *releasing builds* don't need to be so tightly coupled.
  
> > What's the solution you're proposing? Everyone rely solely on git
> > tags?
> 
> Yes.
> 
> And those who insist on using tag+embedded should make absolutely sure they always tag the very commit that bumped the embedded string. Package archives can continue to support embedded strings (by themselves or as duplicated data), but encourage the use of tags. Package archives can "embedded" the version by using it as part of the name of the shipped archive and the top-level directory (as we already do).

That works for the tarball model. Doesn't work for working directly with repositories.
  
> I don't actually want to argue about this at this time. It's like spaces vs tabs, or merge vs rebase.

Those are good examples. You should use what everyone else is using in the development context (the analogy being the "Version" header field).

> Sole-sucking really.

My feet are dry.

> I want to achieve something here and every time I wade unprepared into these conversations, it sucks up some of the energy that I should preserve to actually get something done in this domain.

I, too, would rather not spend energy wrangling elisp versioning schemes.
I don't see git tags as a panacea here, though. I hope you'll reconsider at some point.

**Comment by alphapapa** [comment] 2024-02-08 15:31
FWIW, I don't enjoy having to do the update-version-header-for-release, push-new-version, update-version-header-post-release (i.e. vN+1-pre) dance, for the sake of GNU ELPA.  But it's not that bad, and it guarantees that only one commit of the main package file has a certain version number in the header.  It's become a habit for me, after being part of my checklists for a while.

**Comment by tarsius** [comment] 2024-02-08 20:46
@alphapapa I have created [`sisyphus`](https://github.com/magit/sisyphus) to make that less painful.  Nowadays it also handles other parts of the release process, but bumping the version in the release and after the release, and catching common errors while doing so, was the initial motivation that let to the creation of this package (and its name).

Since I have stopped bumping version strings after releases, and don't recommend doing that anymore, it does not do that by default anymore.  To re-enable that, do `(setq sisyphus-non-release-bump-header t sisyphus-non-release-suffix ".50-git")`.

There is currently no support for increasing the last part of the version string before appending "-git"/"-pre" (without the ".50" part), but if there is interest I could implement that.

See its docstring for another iteration of my view on the matter.
