### ISSUE TITLE
Error in scala-mode

### ISSUE THREAD

**Issue by wedens** [tarsius/hl-todo#53] opened 2020-05-29 18:21 UTC
When I open some scala file that contains "TODO", I get this error:
```
Debugger entered--Lisp error: (args-out-of-range 0 21)
  remove-list-of-text-properties(0 21 (display face font-lock-multiline))
  font-lock-default-unfontify-region(0 21)
  font-lock-unfontify-region(0 21)
  font-lock-default-fontify-region(0 2 nil)
  font-lock-fontify-region(0 2 nil)
  hl-todo-mode()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook scala-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook scala-mode-hook))
  run-mode-hooks(scala-mode-hook)
  scala-mode()
```
If I reopen the same file, it opens without any errors.

I can reproduce it with .scala file that contains just `new RuntimeException("TODO") // TODO` line

**Comment by tarsius** [comment] 2020-05-29 18:30
I cannot reproduce that. Did you try reproducing it starting from `emacs -Q`?

**Comment by wedens** [comment] 2020-05-30 09:20
It doesn't happen every time the file is opened. I may need to reopen the file or restart emacs several times to reproduce the issue.

> Did you try reproducing it starting from emacs -Q?
No. I've tried to reproduce it with as much of my configuration disabled as possible and the error still occurs.

**Comment by tarsius** [comment] 2020-05-31 16:20
This might be an issue in your setup (including additional packages), or it might be an issue with `scala-mode`.  It might also be a `hl-todo` issue, but that is much less likely.

I am closing this.  You probably have no choice but to really start from `emacs -Q`.  If you provide more information, then I might be able to help but as it stands I would have to resort to guessing.

Here's a guess: We just had a similar issue with `tex-mode`: #52. Something in your setup might make the same mistake and the fix might be similar as well.

**Closed** 2020-05-31 16:20 UTC
Labels: unconfirmed
